<Project>
  <PropertyGroup>
    <ApiSportsSdkAbstractionsVersion>1.0.5</ApiSportsSdkAbstractionsVersion>
    <ApiSportsSdkCoreVersion>1.0.5</ApiSportsSdkCoreVersion>
    <ApiSportsSdkAflVersion>1.0.0</ApiSportsSdkAflVersion>
    <ApiSportsSdkBaseballVersion>1.0.0</ApiSportsSdkBaseballVersion>
    <ApiSportsSdkBasketballVersion>1.0.0</ApiSportsSdkBasketballVersion>
    <ApiSportsSdkFootballVersion>1.1.1</ApiSportsSdkFootballVersion>
    <ApiSportsSdkFormula1Version>1.0.3</ApiSportsSdkFormula1Version>
    <ApiSportsSdkHandballVersion>1.0.0</ApiSportsSdkHandballVersion>
    <ApiSportsSdkHockeyVersion>1.0.0</ApiSportsSdkHockeyVersion>
    <ApiSportsSdkMmaVersion>1.0.0</ApiSportsSdkMmaVersion>
    <ApiSportsSdkNbaVersion>1.0.0</ApiSportsSdkNbaVersion>
    <ApiSportsSdkNflVersion>1.0.0</ApiSportsSdkNflVersion>
    <ApiSportsSdkRugbyVersion>1.0.0</ApiSportsSdkRugbyVersion>
    <ApiSportsSdkVolleyballVersion>1.0.0</ApiSportsSdkVolleyballVersion>
    <ApiSportsSdkLoggingMicrosoftVersion>1.0.0</ApiSportsSdkLoggingMicrosoftVersion>
  </PropertyGroup>
</Project>
