<Project>
  <PropertyGroup>
    <ApiSportsSdkAbstractionsVersion>1.0.4</ApiSportsSdkAbstractionsVersion>
    <ApiSportsSdkCoreVersion>1.0.4</ApiSportsSdkCoreVersion>
    <ApiSportsSdkAflVersion>0.1.0</ApiSportsSdkAflVersion>
    <ApiSportsSdkBaseballVersion>0.1.0</ApiSportsSdkBaseballVersion>
    <ApiSportsSdkBasketballVersion>0.1.0</ApiSportsSdkBasketballVersion>
    <ApiSportsSdkFootballVersion>1.0.4</ApiSportsSdkFootballVersion>
    <ApiSportsSdkFormula1Version>1.0.3</ApiSportsSdkFormula1Version>
    <ApiSportsSdkHandballVersion>0.1.0</ApiSportsSdkHandballVersion>
    <ApiSportsSdkLoggingMicrosoftVersion>1.0.0</ApiSportsSdkLoggingMicrosoftVersion>
  </PropertyGroup>
</Project>
